language: c
dist: bionic

cache:
  - ccache

env:
  global:
    - CJSON_HIDE_SYMBOLS=1

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - env: OPTIONAL=true
  include:
    - name: "Sachi tests"
      os: linux
      language: c
      compiler: clang
      env: TESTING=sachi
      addons:
        apt:
          packages:
            - gdb
            - xvfb

script:
  - ./autogen.sh
  - ./configure
  - make sachi
  - chmod a+x sachi/sachi
  - ./sachi/sachi