language: c
dist: bionic

cache:
  - ccache

env:
  global:
    - CJSON_HIDE_SYMBOLS=1

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - env: OPTIONAL=true
  include:
    - name: "Sachi tests"
      os: linux
      language: c
      compiler: clang
      env: TESTING=sachi
      addons:
        apt:
          packages:
            - gdb
            - xvfb

# Travis provides only 2 cores, so don't overdo the parallelism and waste memory.
before_script:
  # -Og is much faster than -O0
  - CFLAGS="${CFLAGS} -Og" ./configure
  - make -j4
  - make sachiexe

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      XVFB_RUN=xvfb-run;
    fi
    $XVFB_RUN make buildbottest TESTOPTS="-j4 -uall,-cpu"