language: c
dist: bionic

cache:
  - ccache

env:
  global:
    - CJSON_HIDE_SYMBOLS=1

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - env: OPTIONAL=true
  include:
    - name: "Sachi tests"
      os: linux
      language: c
      compiler: clang
      env: TESTING=sachi
      script:
        - make check
  include:
    - name: "Sachi build"
      os: linux
      language: c
      compiler: clang
      script:
        - make
        - chmod a+x sachi/sachi
        - sachi/sachi

before-script:
  - ./autogen.sh
  - ./configure
